### ISSUE TITLE
Borders of some buttons missing in iframe

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/area-model-common#186] opened 2019-06-11 13:42 UTC
**Test Device**

MacBook Air

**Operating System**

macOS 10.14.5

**Browser**

Safari 12.1.1

**Problem Description**

For https://github.com/phetsims/QA/issues/338, https://github.com/phetsims/QA/issues/339, https://github.com/phetsims/QA/issues/340, and https://github.com/phetsims/QA/issues/341. If you view any of the AM sims in an iframe, the borders of some of the buttons are missing.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/59276783-305ec180-8c1c-11e9-9e71-50609c171e18.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Area Model Introduction‬
URL: https://phet-dev.colorado.edu/html/area-model-introduction/1.2.0-rc.2/phet/area-model-introduction_all_phet.html
Version: 1.2.0-rc.2 2019-06-06 16:30:20 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Language: en-US
Window: 1440x837
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment] 2019-06-18 17:15
I can't reproduce this locally, but it might be due to the high-DPI screen. I have identical OS/Safari versions, however the pixel ratio on the test device is 1:1.

I'm honestly not sure how to try to work around this type of visual issue. @ariel-phet thoughts?

**Comment by ariel-phet** [comment] 2019-07-01 22:10
@jonathanolson @lmulhall-phet I am going to have to look at this one in person.

@jonathanolson perhaps the work around would be a slightly thicker stroke to the buttons? @jonathanolson can we try that first, just add one pixel to the stroke (or perhaps coordinate with @lmulhall-phet or @KatieWoe to adjust the pixel width until the problem goes away?)

If it only needs a minor thickness adjustment, that seems like an easy workaround.

**Comment by jonathanolson** [comment] 2019-07-09 17:18
I've slightly increased the stroke on master and the release branches. @lmulhall-phet, does that resolve the issue on master?

**Comment by lmulhall-phet** [comment] 2019-07-24 22:11
I guess there's no out-of-the-box way to test a sim in an iframe on master, so I ended up testing http://phettest.colorado.edu/area-model-introduction/area-model-introduction_a11y_view.html. The borders aren't perfect, but they're pretty good.

![Screen Shot 2019-07-24 at 4 08 22 PM](https://user-images.githubusercontent.com/31285590/61832206-9ea6be80-ae2d-11e9-9530-9d90d50c86e2.png)

Back to you, @jonathanolson.

**Comment by jonathanolson** [comment] 2019-07-25 07:50
@ariel-phet I'm not aware of a better fix/workaround at the moment, but that looks better. Should I bump area-model for another round of RC testing?

**Comment by ariel-phet** [comment] 2019-07-25 16:45
@jonathanolson that works for me and seems like an easy and acceptable solution. Yes, go ahead and go to next RC. Closing

**Closed by ariel-phet** 2019-07-25 16:45 UTC
Labels: design:polish, type:bug
