### ISSUE TITLE
Area Model Introduction Box Leaves Trace

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/area-model-common#173] opened 2019-01-14 21:50 UTC
For https://github.com/phetsims/QA/issues/230 on Mac OS 10.11.6 on Safari when dragging the area model around using the circle attached on the bottom right of the area sometimes a section of the circle will stay animated to a position the cursor was previously. I haven't been able to determine an exact set of steps to reproduce, but the bug occurs most ofter the draggable section is moved from position to position rapidly. I have attached screenshots of the issue, where the trace can be seen in the third row and second column. Let me know if there are any issues replicating the bug and I can try to get a specific way of reproducing it.
![screen shot 2019-01-14 at 2 36 53 pm](https://user-images.githubusercontent.com/30352536/51143322-89603000-180b-11e9-8660-bfec79c619a7.png)
![screen shot 2019-01-14 at 2 37 03 pm](https://user-images.githubusercontent.com/30352536/51143337-8ebd7a80-180b-11e9-9dc3-a6782ceeb7bd.png)

**Comment by jonathanolson** [comment] 2019-05-09 20:42
I applied a hopeful workaround. I'm curious if you are still able to reproduce if running this off of master or not.

In general, if the workaround works I'd like to keep it, otherwise I'd like to remove it and probably mark as wont-fix.

**Comment by jonathanolson** [comment] 2019-05-29 23:09
@KatieWoe do you know if this is possible to reproduce off of master?

**Comment by KatieWoe** [comment] 2019-05-30 14:53
It does occur off of master as of this morning (5/30/19).
![yesonmaster](https://user-images.githubusercontent.com/41024075/58641401-5b5e2280-82b8-11e9-8b9f-ce005624bac0.gif)

**Comment by jonathanolson** [comment] 2019-05-30 15:35
@ariel-phet let me know how much more time should be spent on workarounds? I don't have any great leads forward, but I could look more into why Firefox seems to have a lot of SVG repaint issues lately.

**Comment by KatieWoe** [comment] 2019-05-30 20:51
For master check I was on Win 10 Firefox 67

**Comment by ariel-phet** [comment] 2019-05-30 20:53
I tried Win 7 with firefox off master, and could not reproduce. This seems somewhat transient (clicking away fixes it). I think we are going to mark as `wontfix`

**Closed** 2019-05-30 20:54 UTC
Labels: type:bug, type:wontfix
