### ISSUE TITLE
Grid lines appearing when changing Grid size in FireFox

### ISSUE THREAD

**Issue by etwa4650** [phetsims/area-model-common#180] opened 2019-05-16 17:49 UTC
For https://github.com/phetsims/QA/issues/318

 <b>Operating System</b>

  Mac OS 10.13.6

  <b>Browser</b>

  Firefox 66.0.5

  <b>Problem Description</b>

  When in the Partition sim, with the Gridlines checkbox turned off, if you change the size of the Grid, some gridlines will appear.

  <b>Steps to Reproduce</b>

1:Open the sim with firefox on Mac
2: Uncheck the gridlines checkbox
3: Move around/Change the size of the grid

  <b>Visuals</b>

https://drive.google.com/open?id=1P2VlACBgSm74tmev1LnEVRDruRbTX-ss

**Comment by jonathanolson** [comment] 2019-05-23 15:13
I've tried a few mitigation techniques, have a few more things to try.

**Comment by jonathanolson** [comment] 2019-05-29 19:16
My Firefox updated to 67.0 and now I'm unable to reproduce (MacOS 10.14.3):

<img width="1410" alt="Screen Shot 2019-05-29 at 1 12 34 PM" src="https://user-images.githubusercontent.com/480878/58584611-df120380-8213-11e9-8013-c26abbf2e6ef.png">

I tried to duplicate all settings (and guessed query parameters).

Can anyone else confirm if this is still happening, or if Firefox 67 solved this issue?

**Comment by KatieWoe** [comment] 2019-05-29 19:42
I'm still seeing it.

**Comment by ariel-phet** [comment] 2019-06-04 06:46
Firefox on Mac is a barely used platform (0.3% of our overall website usage), considering that this bug minor -- as in it goes away as you move, basically just a visual distraction -- and no obvious pedagogical consequences, it does not seem worth fixing. 

Closing as `wontfix`

**Closed** 2019-06-04 06:46 UTC
Labels: type:bug, type:wontfix
