### ISSUE TITLE
Adjust touch areas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#80] opened 2018-02-01 20:47 UTC

**Comment by amanda-phet** [comment] 2018-02-06 22:10
Is this a duplicate of #16? (Hard to tell as neither has a description). 

What we discussed was adjusting the smaller areas to be larger for touch, such as the accordion open/close button. 

In the Introduction sim we'd like the title bar to be clickable to close, even without at title. 

The touch areas (and perhaps mouse areas?) around the corner drag handle, as well as the partition drag handles, should be larger.

**Comment by jonathanolson** [comment] 2018-02-14 08:00
I've done my best initial implementation, can you check?

**Comment by amanda-phet** [comment] 2018-02-14 17:46
The calculation panel is working as described above. 

I'm not seeing a difference in the mouse touch areas in the latest dev versions you shared with me last night. Perhaps I shouldn't be using the phrase "touch areas" since that is usually for tablets. The "mouse areas" also need to be larger for laptop use. I just took a look and it seems that was my fault for not being clear. 

<img width="527" alt="screen shot 2018-02-14 at 10 44 19 am" src="https://user-images.githubusercontent.com/7852916/36219281-1216d20e-1174-11e8-8d05-bf34cc82e7e4.png">


If we can't adjust the "mouse areas" by Friday I will do the interview on an iPad, but we should still increase the mouse area at some point.

**Comment by jonathanolson** [comment] 2018-02-15 06:26
Usually we'd just increase the size of the control to be bigger, since the mouse interaction usually works in an "accurate" (non-expanded) fashion.

For instance, in this case:
![area-model-crowded](https://user-images.githubusercontent.com/480878/36243346-57bba9c8-11de-11e8-9702-141388fa6220.PNG)
If we expanded any "mouse" areas, you would either get into a case where you mouse over A but it drags B instead, or vice versa.

If the drag handles are too small to be clicked on accurately, I'd definitely recommend we resize the actual controls.

**Comment by amanda-phet** [comment] 2018-02-15 21:38
1. I think a larger "knob" is a good idea, and here is one that is 50% larger with a slightly longer handle.

![screen shot 2018-02-15 at 2 38 16 pm](https://user-images.githubusercontent.com/7852916/36282301-f1db8bfc-125d-11e8-92bd-d226da011939.png)


2. The touch area for the knob will still be larger, but doesn't need to extend quite as far out. The touch AND pointer areas for the triangle handles will be square. In the worst case scenario they will overlap, and the triangle knobs (for the partition lines) should take priority. 

![screen shot 2018-02-15 at 2 39 24 pm](https://user-images.githubusercontent.com/7852916/36282296-ed31c2ec-125d-11e8-9116-76047fab2e4a.png)

**Comment by jonathanolson** [comment] 2018-02-15 22:01
Implemented, with slight improvements discussed in Slack.

I temporarily made the lines thinner to show this. When at the closest it can be:
![area-model-touch-area-1](https://user-images.githubusercontent.com/480878/36283207-01412d60-1261-11e8-87b2-d98908559a50.PNG)

and more separated:
![area-model-touch-area-2](https://user-images.githubusercontent.com/480878/36283215-057fabea-1261-11e8-87f7-26b68b238cd9.PNG)

Is that sufficient?

**Comment by amanda-phet** [comment] 2018-02-15 22:05
That looks great to me! Thanks so much! 

I think I'll use the iPad tomorrow anyway for the bulk of the interview since this is a younger student, but put the computer in front of her too to see if she has any trouble. After interviews I'll close the issue if all seems good.

**Comment by amanda-phet** [comment] 2018-02-16 20:30
Oops, I forgot to put the laptop version in front of the 2nd grader today :( However I think it is a huge improvement and I think the larger handle and touch areas are sufficient. 

One more touch area tweak: Can you make the touch area around the expand/collapse buttons larger? They seem smaller than 40x40, and could definitely use the extra space that the other controls get. 

![screen shot 2018-02-16 at 1 28 36 pm](https://user-images.githubusercontent.com/7852916/36327928-6f4a0702-131d-11e8-87eb-673f28214d5a.png)

**Comment by jonathanolson** [comment] 2018-02-16 21:19
Done. Also note that the titles (for the accordion boxes on the right) are clickable to toggle, in addition to the entire accordion box on the partition screen for the calculation.

**Comment by amanda-phet** [comment] 2018-02-16 21:33
Yes, I confirmed that behavior, but still thought a larger area for that expand/collapse button made sense. 

Thanks! All is looking good to me.

**Comment by pixelzoom** [comment] 2018-04-09 22:59
Reopening.

@amanda-phet Do you realize that clicking _anywhere_ in the status bar sends you back to the level-selection buttons and clears your score?  Is that really desired? (I think not.) If so, why aren't we doing it in other sims.

**Comment by samreid** [comment] 2018-04-16 23:41
I noticed the same problem and described it in https://github.com/phetsims/area-model-common/issues/115

**Comment by amanda-phet** [comment] 2018-04-17 16:02
>@amanda-phet Do you realize that clicking anywhere in the status bar sends you back to the level-selection buttons and clears your score? Is that really desired? (I think not.) If so, why aren't we doing it in other sims.

I did not realize this and @jonathanolson has fixed this behavior.

**Closed by amanda-phet** 2018-04-17 16:02 UTC
