### ISSUE TITLE
Middle of Red Partition Line Disapears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#167] opened 2018-07-31 17:52 UTC
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome 68.0.3440.75
**Problem description:**
In sims with a red partition line it is possible to make the middle of that line disappear when it is placed to the far left of the graph.  This seems to mostly appear on windows in chrome, but can happen less frequently on macs.  For https://github.com/phetsims/QA/issues/157
**Steps to reproduce:**
1. Open the sim on a Windows device in chrome.  Area Model Decimals will work
2. Go to a screen that has a graph with partition lines.  (In Area Model Decimals this is the only screen)
3. The shaded area of the model must have a height of at least 4/5 of the possible area.  It does not matter how wide the shaded area is, as long as the red partition line appears.  The blue partition may be anywhere on the screen, but at the top will make the bug easier to see.
4. There are two ways I have found to accomplish this.  Either try to drag the red partition line past the graph to the right and let the line snap back to the far left.  Or, you can place the red partition line on the far left manually.

When the line arrives at the far left the middle of the line will sometimes be missing.  This seems to occur frequently on Window with chrome, and less frequently on Mac with chrome.  Have not found or reproduced on other devices or browsers.  This does not seem to happen with the blue partition line.

**Screenshots:**
![line](https://user-images.githubusercontent.com/41024075/43477226-e3b83106-94b7-11e8-90d2-e019f89b4108.PNG)

<details>
<summary><b>Troubleshooting information</b></summary>
Name: ‪Area Model Decimals‬
URL: https://phet-dev.colorado.edu/html/area-model-decimals/1.1.0-dev.1/phet/area-model-decimals_en_phet.html
Version: 1.1.0-dev.1 2018-07-26 17:22:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"area-model-common":{"sha":"796b9997","branch":"master"},"area-model-decimals":{"sha":"b2584dea","branch":"master"},"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0353caeb","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"688f8993","branch":"master"},"dot":{"sha":"54f7fb7d","branch":"master"},"joist":{"sha":"4ac76566","branch":"master"},"kite":{"sha":"6bd3398c","branch":"master"},"phet-core":{"sha":"9c242cdc","branch":"master"},"phet-io":{"sha":"ca17e38a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"6091622c","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"51f1f524","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"3d0ed29f","branch":"master"},"phet-io-wrappers":{"sha":"45a360ca","branch":"master"},"phetcommon":{"sha":"d4196e1e","branch":"master"},"query-string-machine":{"sha":"4178d27a","branch":"master"},"scenery":{"sha":"5347f0ef","branch":"master"},"scenery-phet":{"sha":"412b369c","branch":"master"},"sherpa":{"sha":"79fb5b8c","branch":"master"},"sun":{"sha":"6a383379","branch":"master"},"tambo":{"sha":"93107274","branch":"master"},"tandem":{"sha":"0c6d2f43","branch":"master"},"twixt":{"sha":"a73e9257","branch":"master"},"vegas":{"sha":"6b3c902c","branch":"master"},"vibe":{"sha":"960a83ef","branch":"master"}}
</details>

**Comment by jonathanolson** [comment] 2018-08-30 15:05
Was not able to reproduce on Win10 desktop (Chrome/68.0.3440.106) over ~5min of testing. I'm curious if it's only on this laptop (or other laptops) that the bug happens. @KatieWoe would it be possible to test a Win10 desktop to see if it still occurs (or of there are more specific instructions - it may relate to screen size also).

**Comment by KatieWoe** [comment] 2018-08-30 15:45
@jonathanolson I just tested master on the windows 10 laptop and it happened on the first try, so it is still occurring.  I don't really have a windows desktop among the testing devices.  Do you know anywhere I could test on a desktop?

**Comment by KatieWoe** [comment] 2018-08-30 15:52
I made a gif to show you the behavior in action.
![line](https://user-images.githubusercontent.com/41024075/44863414-4fb2d200-ac3a-11e8-95a1-1e5d4fa5d5ed.gif)

**Comment by lmulhall-phet** [comment] 2018-08-30 21:59
@jonathanolson, I can reproduce fairly easily on my MacBook Air (macOS 10.13.6 + Chrome 68.0.3440.106). Here's a gif:

![thing](https://user-images.githubusercontent.com/31285590/44881638-940b9580-ac6d-11e8-8cc6-7846e2780d36.gif)

**Comment by jonathanolson** [comment] 2018-09-09 20:08
There is just nothing I can do on the devices I have to reproduce this. I'm curious if it relates to GPU texture size (Chrome likes to tile things into e.g. 512x512 squares and each is updated somewhat independently, and it looks like some squares aren't getting the updates).

I'll plan to investigate when I'm on campus on Tuesday. Additionally, Chrome has now updated to version 69, so I'm curious if there's a chance this was fixed in that update.

**Comment by KatieWoe** [comment] 2018-09-10 15:05
@jonathanolson I did just take a look on master, and I'm now having trouble reproducing it, so the chrome update may have solved it.  I'll be happy to help you investigate on Tuesday if you need.  Just let me know.

**Comment by jonathanolson** [comment] 2018-09-20 06:35
This is now not reproducible after Chrome 69. Closing.

**Closed by jonathanolson** 2018-09-20 06:35 UTC
Labels: type:bug
